# Generated by Django 5.1.1 on 2024-09-19 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="github_username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
