# Generated by Django 5.1.1 on 2024-09-19 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_customuser_github_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="google_token",
        ),
    ]
