# Generated by Django 5.1.1 on 2024-09-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_githubaccount_delete_customuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="githubaccount",
            name="repositories",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
