# Generated by Django 5.1.1 on 2024-09-27 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_githubaccount_repositories"),
    ]

    operations = [
        migrations.CreateModel(
            name="SelectedRepository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repo_name", models.CharField(max_length=255)),
                ("repo_url", models.URLField()),
                (
                    "github_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_repositories",
                        to="api.githubaccount",
                    ),
                ),
            ],
        ),
    ]
